# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.network "private_network", ip: "10.10.10.26"
  # config.vm.network "public_network"

   config.vm.synced_folder "./..", "/home/vagrant/forcom-test"

  config.vm.provider "virtualbox" do |vb|
	vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end

end
